[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.install]
cmds = ["dotnet restore CollabSpace.csproj"]

[phases.build]
cmds = ["dotnet publish CollabSpace.csproj -c Release -o out --no-restore"]

[start]
cmd = "dotnet out/CollabSpace.dll"